weather-api:
  base-url: http://api.weatherapi.com/v1/current.json
  api-key: bb0362724b964c08bfa140029260307
  location: Buenos Aires
alerta:
  destinatarios:
    - admin@clima.com
    - emergencias@clima.com
    - meteorologia@clima.com
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: tomi161205@gmail.com
    password: qaac road apkd ekha
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true